version: '3.8'

services:
  db:
    image: mysql:8.0.31
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: projet
      MYSQL_USER: projet
      MYSQL_PASSWORD: projet
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
      - ./db-init.d:/docker-entrypoint-initdb.d
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    networks:
      - local
    environment:
      - PMA_ARBITRARY=1

  wildfly:
    image: quay.io/wildfly/wildfly:latest-jdk17
    ports:
      - "8080:8080"
    volumes:
      - ./build/exploded:/opt/jboss/wildfly/standalone/deployments:rw
#      - ./docker/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:ro
    environment:
      - DB_ADDR=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=maria
    networks:
      - local

volumes:
  db:

networks:
  local: