version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'projet'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - db_prod:/var/lib/mysql
    # - ./db-init.d:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  db_prod:

networks:
  mynetwork:
    driver: bridge
