version: '3.8'

services:
  db:
    image: mysql:8.0.31
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
      - ./db-init.d:/docker-entrypoint-initdb.d
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    networks:
      - local
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

  wildfly:
    image: quay.io/wildfly/wildfly:latest-jdk17
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./build/exploded:/opt/jboss/wildfly/standalone/deployments:rw
    networks:
      - local

volumes:
  db:

networks:
  local: